url = "https://www.houzz.ru/professionals/"

data = [{'Дизайнеры интерьера': 'dizayn-interyera'},
        {'Архитекторы': 'Arkhitektory'},
        {'Декораторы и стилисты': 'dekoratory-i-stilisty-interiera'},
        {'Проектирование и строительство': 'proektirovanie-i-stroitelystvo'},
        {'Бани и сауны': 'bani-i-sauny'},
        {'Баccейны': 'basseyny'},
        {'Агенства недвижимости': 'agentstva-nedvizhimosti'},

        {'Ремонт и отделка квартир и домов': 'remont-i-otdelka-kvartir-i-domov'},
        {'Специалисты по ремонту кухни': 'spetsialisty-po-remontu-kukhni'},
        {'Ремонт ванных': 'remont-vannyh'},
        {'Столешницы, плитка, отделочный камень': 'plitka-otdelochnyy-kameny-i-stoleshnitsy'},
        {'Окна': 'okna'},
        {'Двери': 'dveri'},
        {'Отделочные материалы': 'otdelochnye-materialy'},
        {'Строительные материалы': 'stroitelynye-materialy'},
        {'Электромонтаж': 'elektromontazh'},
        {'Отопление, вентиляция, кондиционирование': 'sistemy-ovk'},
        {'Сантехнические работы': 'santehnicheskie-raboty'},

        {'Мебель и аксессуары': 'mebely-i-aksessuary'},
        {'Шторы и жалюзи': 'shtory-i-zhalyuzi'},
        {'Производство и установка кухонь': 'proizvodstvo-i-ustanovka-kuhony'},
        {'Гардеробные и кладовые комнаты': 'garderobnye-i-kladovye-komnaty'},
        {'Корпусная мебель': 'korpusnaya-mebely'},
        {'Освещение': 'osveshchenie'},
        {'Плотницкие и столярные работы': 'plotnichnye-raboty'},
        {'Художники и ремесленники': 'hudozhniki-i-remeslenniki'},
        {'Ковры и напольные покрытия': 'kovry-i-napolynye-pokrytiya'},
        {'Художественная ковка': 'hudozhestvennaya-kovka'},
        {'Обивка и текстиль': 'obivka-i-tekstily'},
        {'Бытовая техника': 'bytovaya-tehnika'},
        {'Предметный дизайн': 'predmetnyy-dizayn'},
        {'Детские и пеленальные': 'detskie-i-pelenalynye'},
        {'Сантехника для ванной и кухни': 'santehnika-dlya-vannoi-i-kuhni'},
        {'Постельные и банные принадлежности': 'postelynye-i-bannye-prinadlezhnosti'},
        {'Ремонт и реставрация мебели': 'restavratsiya-mebeli'},

        {'Ландшафтные дизайнеры': 'landshaftnyy-dizayn'},
        {'Беседки и веранды': 'besedki-i-verandy'},
        {'Обустройство двора и сада': 'obustroystvo-sada'},
        {'Камины и печи': 'kaminy'},
        {'Лестницы и перила': 'lestnitsy-i-perila'},
        {'Заборы и ворота': 'zabory-i-vorota'},
        {'Парники, теплицы и оранжереи': 'parniki-teplitsy-i-orangerei'},
        {'Товары для сада': 'tovary-dlya-sada'},
        {'Камень, асфальт, бетон': 'kameny-asfalyt-beton'},
        {'Винные погреба': 'vinnye-pogreba'},
        {'Кровля и водосточки': 'krovlya-i-vodostoki'},
        {'Сайдинг и облицовка фасада': 'sayding-i-oblitsovka-fasada'},
        {'Гаражные ворота': 'garazhnye-dveri'},
        {'Стрижка деревьев и кустарников': 'strizhka-derevyev-i-kustarnikov'},
        {'Газон и полив': 'gazon-i-poliv'},
        {'Игровые площадки': 'igrovye-ploshchadki'},
        {'Подъездные дорожки и облицовка': 'podaezdnye-dorozhki-i-oblitsovka'},
        {'Солнечная энергия': 'sistemy-solnechnogo-teplosnabzheniya'},
        {'Уличное освещение, визуальные и аудиосистемы': 'vneshnee-osveshchenie-vizualynye-i-audiosistemy'},
        {'Уборка территории': 'uborka-territorii'},

        {'Фотографы': 'photoshooting'},
        {'Умный дом и системы автоматизации мультимедиа': 'umnyy-dom-i-sistemy-avtomatizatsii'},
        {'Помощь при переезде': 'pomoshch-pri-pereezde'},
        {'Уборка квартир и домов': 'uborka-kvartir-i-domov'},
        {'Вызов мусора': 'vyvoz-musora'},
        {'Учебные заведения и ассоциации': 'uchebnye-zavedeniya-i-assotsiatsii'},
        {'Специализированные работы': 'spetsializirovannye-raboty'},
        {'Пресса и блоги': 'pressa-i-blogi'}]